"""
app/api/v1/auth.py
───────────────────
FastAPI router for the Authentication module.

Design principle — "Thin Routers":
  Every endpoint does exactly three things:
    1. Declare request/response schemas (Pydantic validates automatically).
    2. Extract contextual data (user-agent, IP) from the Request.
    3. Delegate entirely to auth_service and return the result.

  No if/else logic, no raw SQL, no business decisions here.
  If you find yourself writing conditional logic in a router, it belongs
  in the service layer instead.
"""

from __future__ import annotations

from typing import Annotated, Optional

from fastapi import APIRouter, Depends, Request, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.dependencies import get_current_user, get_db
from app.models.user import User
from app.schemas.auth import (
    LoginRequest,
    MessageResponse,
    RefreshRequest,
    RegisterRequest,
    RegisterResponse,
    TokenResponse,
)
from app.services import auth_service

router = APIRouter(prefix="/auth", tags=["Authentication"])


@router.post(
    "/register",
    response_model=RegisterResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Register a new member",
    description=(
        "Creates a new gym member account. "
        "The member_id (e.g., S2T101) is auto-generated by the database "
        "and returned in the response — the member must save it for future login. "
        "Initial membership status is PENDING until admin approves payment."
    ),
)
async def register(
    payload: RegisterRequest,
    db: Annotated[AsyncSession, Depends(get_db)],
) -> RegisterResponse:
    return await auth_service.register_member(db, payload)


@router.post(
    "/login",
    response_model=TokenResponse,
    status_code=status.HTTP_200_OK,
    summary="Login with Member ID and password",
    description=(
        "Authenticate using your Member ID (e.g., S2T101) and password. "
        "Admins can also use their email address in the member_id field. "
        "Returns a JWT access token (15 min) and a refresh token (90 days). "
        "After 5 consecutive failures, the account is locked for 30 minutes."
    ),
)
async def login(
    payload: LoginRequest,
    request: Request,
    db: Annotated[AsyncSession, Depends(get_db)],
) -> TokenResponse:
    # Extract device context for refresh token audit trail
    user_agent: Optional[str] = request.headers.get("user-agent")
    ip_address: Optional[str] = (
        request.client.host if request.client else None
    )
    return await auth_service.login(
        db,
        payload,
        user_agent=user_agent,
        ip_address=ip_address,
    )


@router.post(
    "/refresh",
    response_model=TokenResponse,
    status_code=status.HTTP_200_OK,
    summary="Rotate refresh token and issue new access token",
    description=(
        "Exchange a valid refresh token for a new access token + refresh token pair. "
        "The old refresh token is immediately revoked (rolling rotation). "
        "Use this when the access token expires to maintain the 90-day session "
        "without requiring the user to log in again."
    ),
)
async def refresh(
    payload: RefreshRequest,
    db: Annotated[AsyncSession, Depends(get_db)],
) -> TokenResponse:
    return await auth_service.refresh_access_token(db, payload)


@router.post(
    "/logout",
    response_model=MessageResponse,
    status_code=status.HTTP_200_OK,
    summary="Logout and revoke refresh token",
    description=(
        "Revoke the provided refresh token server-side. "
        "The current access token remains valid for up to 15 minutes. "
        "Requires a valid access token in the Authorization header to prevent "
        "anonymous token revocation abuse."
    ),
)
async def logout(
    payload: RefreshRequest,
    db: Annotated[AsyncSession, Depends(get_db)],
    _: Annotated[User, Depends(get_current_user)],  # Requires valid access token
) -> MessageResponse:
    return await auth_service.logout(db, payload)
