"""
app/schemas/auth.py
────────────────────
Pydantic v2 request/response schemas for the Authentication module.

These schemas form the strict API contract between client and server.
Pydantic validates all incoming data BEFORE it reaches the service layer.
Invalid data is rejected with HTTP 422 automatically by FastAPI.
"""

from __future__ import annotations

import uuid
from datetime import date
from typing import Optional

from pydantic import BaseModel, EmailStr, Field, field_validator


# ── Registration ───────────────────────────────────────────────────────────

class RegisterRequest(BaseModel):
    """
    All fields from the registration form.
    member_id is NOT in this request — it's auto-generated by the DB trigger.
    """

    full_name: str = Field(
        ...,
        min_length=2,
        max_length=255,
        examples=["Rahul Sharma"],
    )
    age: int = Field(
        ...,
        ge=10,
        le=100,
        examples=[28],
        description="Member's age. Must be between 10 and 100.",
    )
    gender: str = Field(
        ...,
        examples=["Male"],
        description="One of: Male, Female, Other.",
    )
    phone: str = Field(
        ...,
        pattern=r"^\d{10}$",
        examples=["9876543210"],
        description="10-digit mobile number without country code.",
    )
    email: EmailStr = Field(
        ...,
        examples=["rahul@example.com"],
    )
    address: str = Field(
        ...,
        min_length=5,
        max_length=500,
        examples=["12, Anna Nagar, Trichy - 620001"],
    )
    password: str = Field(
        ...,
        min_length=8,
        max_length=128,
        examples=["MyPass@123"],
        description="Min 8 chars, must include uppercase, lowercase, and a digit.",
    )
    plan_id: uuid.UUID = Field(
        ...,
        description="UUID of the selected gym plan (Monthly / Annually / Special).",
    )

    @field_validator("gender")
    @classmethod
    def validate_gender(cls, v: str) -> str:
        allowed = {"Male", "Female", "Other"}
        if v not in allowed:
            raise ValueError(f"Gender must be one of: {', '.join(sorted(allowed))}")
        return v

    @field_validator("password")
    @classmethod
    def validate_password_strength(cls, v: str) -> str:
        """
        Enforce minimum password policy:
          - At least one uppercase letter (A-Z)
          - At least one lowercase letter (a-z)
          - At least one digit (0-9)
        Regex-only validation would be opaque — explicit checks give clear messages.
        """
        errors = []
        if not any(c.isupper() for c in v):
            errors.append("at least one uppercase letter")
        if not any(c.islower() for c in v):
            errors.append("at least one lowercase letter")
        if not any(c.isdigit() for c in v):
            errors.append("at least one digit")
        if errors:
            raise ValueError(f"Password must contain {', '.join(errors)}.")
        return v


class RegisterResponse(BaseModel):
    """
    Returned after successful registration.
    The member_id is the most important field — member must save it for login.
    """

    member_id: str = Field(examples=["S2T101"])
    full_name: str = Field(examples=["Rahul Sharma"])
    plan_name: str = Field(examples=["Monthly"])
    message: str = Field(
        examples=["Registration successful. Your Member ID is S2T101. Please login."]
    )


# ── Login ──────────────────────────────────────────────────────────────────

class LoginRequest(BaseModel):
    """
    Members log in with their auto-generated member_id (not email).
    Admins also use this endpoint with their email as the identifier.
    """

    member_id: str = Field(
        ...,
        examples=["S2T101"],
        description="Your Member ID (e.g., S2T101) or admin email.",
    )
    password: str = Field(..., examples=["MyPass@123"])


# ── User Representation ────────────────────────────────────────────────────

class UserOut(BaseModel):
    """
    Safe user representation returned in token responses.
    Never includes password_hash, failed_login_attempts, or locked_until.
    """

    id: uuid.UUID
    member_id: Optional[str] = Field(
        default=None,
        description="Null for admin accounts.",
    )
    email: str
    role: str = Field(description="'admin' or 'member'")
    full_name: Optional[str] = Field(
        default=None,
        description="From members_profile. Null for admins.",
    )
    membership_status: Optional[str] = Field(
        default=None,
        description="ACTIVE | EXPIRED | PENDING | SUSPENDED. Null for admins.",
    )
    plan_name: Optional[str] = Field(
        default=None,
        description="Selected gym plan name. Null for admins.",
    )
    expiry_date: Optional[date] = Field(
        default=None,
        description="Membership expiry date. Null until first payment approved.",
    )

    model_config = {"from_attributes": True}


# ── Token Responses ────────────────────────────────────────────────────────

class TokenResponse(BaseModel):
    """
    Full auth response returned on successful login or token refresh.
    The client must store BOTH tokens:
      - access_token in memory (never localStorage for security).
      - refresh_token in an HttpOnly cookie or secure storage.
    """

    access_token: str
    refresh_token: str
    token_type: str = "bearer"
    expires_in: int = Field(
        description="Access token lifetime in seconds (default 900 = 15 min)."
    )
    user: UserOut


# ── Refresh & Logout ───────────────────────────────────────────────────────

class RefreshRequest(BaseModel):
    """Body for POST /auth/refresh and POST /auth/logout."""

    refresh_token: str = Field(
        ...,
        min_length=10,
        description="The raw refresh token received during login.",
    )


# ── Generic ────────────────────────────────────────────────────────────────

class MessageResponse(BaseModel):
    """Simple success/info message response."""

    message: str
