"""
app/models/user.py
───────────────────
SQLAlchemy ORM model for the `users` table.

Stores authentication credentials and role for all users (admin + member).
The member_id column (e.g., "S2T101") is NULL for admin accounts and
auto-generated by a PostgreSQL BEFORE INSERT trigger for member accounts.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

import sqlalchemy as sa
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.member_profile import MemberProfile
    from app.models.refresh_token import RefreshToken


class User(Base, TimestampMixin):
    __tablename__ = "users"

    # ── Primary Identity ───────────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        sa.UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=sa.text("gen_random_uuid()"),
        doc="Internal UUID primary key.",
    )

    member_id: Mapped[Optional[str]] = mapped_column(
        sa.String(20),
        unique=True,
        nullable=True,
        index=True,
        doc=(
            "Human-readable sequential ID (e.g., S2T101). "
            "Auto-assigned by PostgreSQL BEFORE INSERT trigger for members. "
            "NULL for admin accounts — admins log in with email."
        ),
    )

    email: Mapped[str] = mapped_column(
        sa.String(255),
        unique=True,
        nullable=False,
        index=True,
        doc="Unique email address. Used as admin login identifier.",
    )

    password_hash: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        doc="bcrypt hash of the user's password (cost=12). Never stored in plaintext.",
    )

    # ── Role & Status ──────────────────────────────────────────────────────
    role: Mapped[str] = mapped_column(
        sa.Enum("admin", "member", name="user_role"),
        nullable=False,
        default="member",
        server_default="member",
        doc="RBAC role. Only two roles: 'admin' or 'member'.",
    )

    is_active: Mapped[bool] = mapped_column(
        sa.Boolean,
        nullable=False,
        default=True,
        server_default=sa.true(),
        doc="Soft-disable flag. Inactive users cannot log in.",
    )

    # ── Brute-Force Protection ─────────────────────────────────────────────
    failed_login_attempts: Mapped[int] = mapped_column(
        sa.Integer,
        nullable=False,
        default=0,
        server_default="0",
        doc="Consecutive failed login count. Resets to 0 on successful login.",
    )

    locked_until: Mapped[Optional[datetime]] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=True,
        doc=(
            "UTC timestamp until which this account is locked. "
            "NULL means account is not locked. "
            "Set when failed_login_attempts reaches MAX_LOGIN_ATTEMPTS."
        ),
    )

    # ── Relationships ──────────────────────────────────────────────────────
    # lazy="noload" — never load relationships automatically.
    # All related data must be fetched explicitly (select + join or selectinload).
    # This prevents accidental N+1 queries in async context.

    profile: Mapped[Optional["MemberProfile"]] = relationship(
        "MemberProfile",
        back_populates="user",
        uselist=False,
        lazy="noload",
    )

    refresh_tokens: Mapped[list["RefreshToken"]] = relationship(
        "RefreshToken",
        back_populates="user",
        lazy="noload",
    )

    def __repr__(self) -> str:
        return f"<User id={self.id} member_id={self.member_id!r} role={self.role!r}>"
